import React from 'react'
import { createRoot } from 'react-dom/client'
import { App } from './app/App.jsx'

import './styles/base/style.css'
import './styles/base/sticky-header.css'
import './styles/base/page-styles.css'
import './styles/base/source-styles.css'
import './styles/base/design-overhaul.css'
import './styles/base/engagement.css'
import './styles/base/premium.css'
import './styles/base/shell-upgrade.css'
import './styles/pages/interactive.css'
import './styles/pages/auth.css'
import './styles/components/logo.css'
import './styles/components/global-experience.css'
import './styles/components/hero-scene.css'
import './styles/pages/home-page.css'
import './styles/pages/focused-home.css'
import './styles/pages/focused-home-v2.css'
import './styles/pages/method-page.css'
import './styles/pages/plans-page.css'
import './styles/pages/study-domains.css'

createRoot(document.getElementById('app')).render(<React.StrictMode><App /></React.StrictMode>)
