import React from 'react'
import { createRoot } from 'react-dom/client'
import { App } from './app/App.jsx'

import './styles/base/style.css'
import './styles/base/sticky-header.css'
import './styles/base/page-styles.css'
import './styles/base/source-styles.css'
import './styles/base/design-overhaul.css'
import './styles/base/engagement.css'
import './styles/base/premium.css'
import './styles/base/shell-upgrade.css'
import './styles/pages/interactive.css'
import './styles/pages/auth.css'
import './styles/components/logo.css'
import './styles/components/global-experience.css'
import './styles/components/hero-scene.css'
import './styles/pages/home-page.css'
import './styles/pages/focused-home.css'
import './styles/pages/focused-home-v2.css'
import './styles/pages/method-page.css'
import './styles/pages/plans-page.css'
import './styles/pages/study-domains.css'
import './styles/pages/why-page.css'
import './styles/pages/help-page.css'
import './styles/pages/connect-page.css'
import './styles/pages/signin-page.css'
import './components/IntakeCanvas/intake.css'
import './pages/Student/student-dashboard.css'
import './pages/Student/student-mobile.css'
import './pages/Student/student-polish.css'
import './pages/Student/student-tasks.css'
import './pages/Student/student-tasks-overrides.css'
import './pages/Student/student-tasks-interactions.css'
import './pages/Student/student-files.css'
import './pages/Student/student-explain.css'
import './pages/Student/student-payments.css'
import './pages/Student/student-notifications.css'
import './pages/Student/student-help.css'

createRoot(document.getElementById('app')).render(<React.StrictMode><App /></React.StrictMode>)
