import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Bell, BookOpen, ChevronDown, ChevronRight, ClipboardList, CreditCard, FolderOpen, HelpCircle, Home, LogOut, Menu, MessageCircle, PanelLeftClose, PanelLeftOpen, Plus, Settings, ShieldCheck, Sparkles, X } from 'lucide-react'
import { fetchStudentDashboard, formatDate, formatRelativeTime, getTaskJourney } from '../../student/studentDashboardData.js'
import { TaskCreationStudio } from './TaskCreationStudio.jsx'
import logo from '../../assets/logo-bg-removed.png'

const go = (path) => { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')) }
const navItems = [['Dashboard', '/student/dashboard', Home], ['My Tasks', '/student/tasks', ClipboardList], ['Messages', '/student/messages', MessageCircle], ['Files & Deliveries', '/student/deliveries', FolderOpen], ['Explain & Defend', '/student/explain', BookOpen], ['Payments', '/student/payments', CreditCard]]
const moreItems = [['Notifications', '/student/notifications', Bell], ['Help', '/help', HelpCircle], ['Account', '/student/account', Settings]]
const labelOfPath = (path) => { const all = [...navItems, ...moreItems]; const found = all.find(([_, target]) => target === path); return found ? found[0] : 'Dashboard' }
const initials = (student) => (student?.name || student?.displayName || student?.email || 'Student').split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase()
const nameOf = (student) => student?.name || student?.displayName || 'Student'
function ActionButton({ children, onClick, secondary = false }) { return <button className={secondary ? 'student-button student-button--secondary' : 'student-button'} onClick={onClick}>{children}<ChevronRight size={15} /></button> }

function StudentSidebar({ collapsed, setCollapsed, path, model }) { return <aside className={`student-sidebar ${collapsed ? 'is-collapsed' : ''}`}><div className="student-brand"><img src={logo} alt="SolveNest" /><span>SolveNest</span></div><nav aria-label="Student workspace"><p className="student-nav-label">Workspace</p>{navItems.map(([label, target, Icon]) => <button key={target} className={`student-nav-item ${path === target ? 'is-active' : ''}`} onClick={() => go(target)} title={collapsed ? label : undefined}><Icon size={17} /><span>{label}</span>{label === 'Messages' && model.unreadMessages > 0 && <b>{model.unreadMessages}</b>}</button>)}<p className="student-nav-label student-nav-label--lower">Personal</p>{moreItems.map(([label, target, Icon]) => <button key={target} className={`student-nav-item ${path === target ? 'is-active' : ''}`} onClick={() => go(target)} title={collapsed ? label : undefined}><Icon size={17} /><span>{label}</span>{label === 'Notifications' && model.notifications.length > 0 && <b>{model.notifications.length}</b>}</button>)}</nav><button className="student-collapse" onClick={() => setCollapsed((value) => !value)} aria-label={collapsed ? 'Expand navigation' : 'Collapse navigation'}>{collapsed ? <PanelLeftOpen size={17} /> : <PanelLeftClose size={17} />}<span>{collapsed ? 'Expand' : 'Collapse'}</span></button></aside> }
function TopBar({ student, onMenu, onNotifications, onNewTask, path }) { return <header className="student-topbar"><div className="student-context"><button className="student-mobile-menu" onClick={onMenu} aria-label="Open navigation"><Menu size={20} /></button><img className="student-mobile-logo" src={logo} alt="SolveNest" /><span>Student</span><ChevronRight size={14} /><strong>{labelOfPath(path)}</strong></div><div className="student-top-actions"><button className="student-new-task" onClick={onNewTask}><Plus size={17} />New Task</button><button className="student-icon-button" onClick={onNotifications} aria-label="Open notifications"><Bell size={18} /></button><button className="student-profile" onClick={() => go('/student/account')}><span className="student-avatar">{student?.avatarUrl ? <img src={student.avatarUrl} alt="" /> : initials(student)}</span><span>{nameOf(student)}</span><ChevronDown size={14} /></button></div></header> }
function FocusStrip({ action }) { if (!action) return <section className="student-focus student-focus--quiet"><span className="student-focus-marker" /><div><p className="student-overline">YOUR FOCUS</p><h2>You’re all caught up.</h2><p>There are no student actions waiting for you.</p></div><ActionButton secondary onClick={() => go('/student/tasks')}>View active tasks</ActionButton></section>; const task = action.task; return <motion.section className="student-focus" aria-live="polite" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .28 }}><span className="student-focus-marker" /><div><p className="student-overline">{(task?.display?.label || 'ACTION REQUIRED').toUpperCase()}</p><h2>{task?.title || task?.type || 'Your task'}</h2><p>{action.label || 'Open task'} is the next step for this task.</p></div><ActionButton onClick={() => go(action.route || task?.display?.route || '/student/tasks')}>{action.label || 'Open task'}</ActionButton></motion.section> }
function Journey({ task }) { const stages = getTaskJourney(task); const current = stages.find((stage) => stage.status === 'current') || stages[0]; const currentIndex = stages.indexOf(current); return <section className="student-journey"><div className="student-section-heading"><div><p className="student-overline">TASK JOURNEY</p><h2>Where your task is now</h2></div><span className="student-stage-count">{currentIndex + 1} / {stages.length}</span></div><div className="student-rail" role="list" aria-label="Task journey stages">{stages.map((stage, index) => <div className={`student-stage is-${stage.status}`} key={stage.key} role="listitem"><span>{String(index + 1).padStart(2, '0')}</span><b>{stage.label}</b>{index < stages.length - 1 && <i />}</div>)}</div><div className="student-current-stage"><p className="student-overline">{String(currentIndex + 1).padStart(2, '0')} / {current.label.toUpperCase()}</p><strong>{task?.display?.label || 'Task update'}</strong><p>{task?.latestUpdate?.text || task?.latestUpdate || `Your task is currently in ${current.label.toLowerCase()}.`}</p></div></section> }
function StatusPanel({ task }) { return <aside className="student-status-panel"><p className="student-overline">TASK STATUS</p><dl><div><dt>Current</dt><dd>{task?.display?.label || 'Not available'}</dd></div><div><dt>Next</dt><dd>{task?.nextAction?.label || 'No action required'}</dd></div><div><dt>Latest update</dt><dd>{task?.latestUpdate?.text || task?.latestUpdate || 'No update available.'}</dd></div></dl>{task?.expert && <div className="student-expert"><span className="student-expert-mark"><ShieldCheck size={15} /></span><div><small>ASSIGNED EXPERT</small><strong>{task.expert.name}</strong><span>{task.expert.verified ? 'Verified SolveNest expert' : 'SolveNest expert'}</span></div></div>}{task?.display?.key === 'ASSIGNMENT_PENDING' && <p className="student-matching"><span />SolveNest is reviewing suitable expertise.</p>}<ActionButton onClick={() => go(task?.nextAction?.route || '/student/tasks')}>Open task room</ActionButton></aside> }
function ActiveTask({ task, onNewTask }) { if (!task) return <section className="student-empty-inline"><p className="student-overline">START WITH YOUR BRIEF</p><h2>Your workspace begins with one task.</h2><p>Upload an assignment brief and let Solvy structure what comes next.</p><ActionButton onClick={onNewTask}>Create your first task</ActionButton></section>; return <section className="student-active"><div className="student-section-heading"><div><p className="student-overline">CONTINUE</p><h2>{task.title || task.type || 'Untitled task'}</h2><p>{task.subject || task.domain || task.reference || 'Task workspace'}</p></div><span className="student-reference">{task.reference || 'Reference unavailable'}</span></div><div className="student-active-grid"><Journey task={task} /><StatusPanel task={task} /></div></section> }
function TaskList({ tasks }) { const [expanded, setExpanded] = useState(null); return <section className="student-task-list"><div className="student-section-heading"><div><p className="student-overline">MY TASKS</p><h2>Your work, in one place</h2></div><button className="student-link-button" onClick={() => go('/student/tasks')}>View all <ChevronRight size={15} /></button></div>{tasks.length === 0 ? <p className="student-muted-copy">Your submitted tasks will appear here.</p> : <div className="student-ledger" role="list">{tasks.map((task) => <div className="student-task-row" key={task.id || task.reference} role="listitem"><button className="student-task-main" onClick={() => setExpanded(expanded === task.id ? null : task.id)} aria-expanded={expanded === task.id}><span className={`student-state-dot tone-${task.display.tone}`} /><span className="student-task-name"><strong>{task.title || task.type || 'Untitled task'}</strong><small>{task.subject || task.domain || task.reference || 'Task'}</small></span><span className="student-task-state">{task.display.label}</span><span className="student-task-date">{formatDate(task.deadline)}</span><span className="student-task-action">{task.nextAction.label}</span><ChevronDown size={16} /></button>{expanded === task.id && <motion.div className="student-task-expanded" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}><p>{task.latestUpdate?.text || task.latestUpdate || 'No latest update available.'}</p><ActionButton secondary onClick={() => go(task.nextAction.route)}>Open task</ActionButton></motion.div>}</div>)}</div>}</section> }
function Activity({ items }) { return <section className="student-activity"><div className="student-section-heading"><div><p className="student-overline">RECENT ACTIVITY</p><h2>What changed</h2></div></div>{items.length === 0 ? <p className="student-muted-copy">Updates will appear here as your work moves forward.</p> : <div className="student-activity-feed">{items.map((item, index) => <button key={item.id || `${item.createdAt}-${index}`} className="student-activity-item" onClick={() => item.route && go(item.route)}><time dateTime={item.createdAt}>{formatRelativeTime(item.createdAt)}</time><span><strong>{item.title || item.type || 'Task update'}</strong><small>{item.taskTitle || item.taskReference || ''}</small></span><ChevronRight size={15} /></button>)}</div>}</section> }
function NotificationDrawer({ notifications, onClose }) { return <motion.aside className="student-drawer" initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} aria-label="Notifications"><div className="student-drawer-header"><div><p className="student-overline">INBOX</p><h2>Notifications</h2></div><button className="student-icon-button" onClick={onClose} aria-label="Close notifications"><X size={18} /></button></div>{notifications.length === 0 ? <p className="student-muted-copy">You have no new notifications.</p> : notifications.map((item, index) => <button className="student-notification" key={item.id || index} onClick={() => { onClose(); if (item.route) go(item.route) }}><span className="student-state-dot tone-active" /><span><strong>{item.title || item.type || 'Notification'}</strong><small>{item.body || item.taskTitle || ''}</small><time>{formatRelativeTime(item.createdAt)}</time></span></button>)}</motion.aside> }
function DashboardError({ onRetry, access }) { return <section className="student-local-error" role="alert"><p className="student-overline">{access ? 'ACCESS REQUIRED' : 'COULD NOT LOAD'}</p><h2>{access ? 'Sign in to open your student workspace.' : 'We could not load your workspace.'}</h2><p>{access ? 'Your student session is missing or has expired.' : 'We could not retrieve the current workspace data.'}</p><ActionButton onClick={() => access ? go('/login') : onRetry()}>{access ? 'Sign in' : 'Try again'}</ActionButton></section> }
function DashboardSkeleton() { return <div className="student-dashboard-skeleton" aria-label="Loading student workspace"><span /><span /><div><span /><span /></div><span /><span /></div> }
function StudentMobileNav({ onNewTask }) { return <nav className="student-bottom-nav" aria-label="Mobile student workspace"><button onClick={() => go('/student/dashboard')}><Home size={17} /><span>Dashboard</span></button><button onClick={() => go('/student/tasks')}><ClipboardList size={17} /><span>Tasks</span></button><button className="is-primary" onClick={onNewTask}><Plus size={18} /><span>New Task</span></button><button onClick={() => go('/student/messages')}><MessageCircle size={17} /><span>Messages</span></button><button onClick={() => go('/student/account')}><Settings size={17} /><span>More</span></button></nav> }

export function StudentDashboard() {
  const [collapsed, setCollapsed] = useState(() => window.localStorage.getItem('sn-student-sidebar') === 'collapsed')
  const [mobileNav, setMobileNav] = useState(false)
  const [notificationsOpen, setNotificationsOpen] = useState(false)
  const [studioOpen, setStudioOpen] = useState(false)
  const [state, setState] = useState({ loading: true, error: null, model: null })
  const load = () => { const controller = new AbortController(); setState((current) => ({ ...current, loading: true, error: null })); fetchStudentDashboard(controller.signal).then((model) => setState({ loading: false, error: null, model })).catch((error) => { if (error.name !== 'AbortError') setState({ loading: false, error, model: null }) }); return () => controller.abort() }
  useEffect(() => load(), [])
  useEffect(() => { window.localStorage.setItem('sn-student-sidebar', collapsed ? 'collapsed' : 'expanded') }, [collapsed])
  const model = state.model
  const path = window.location.pathname
  const mobileItems = navItems.concat(moreItems)
  const onCreated = () => { load() }
  return <div className="student-app"><StudentSidebar collapsed={collapsed} setCollapsed={setCollapsed} path={path} model={model || { unreadMessages: 0, notifications: [] }} /><div className="student-main"><TopBar student={model?.student} onMenu={() => setMobileNav((value) => !value)} onNotifications={() => setNotificationsOpen(true)} onNewTask={() => setStudioOpen(true)} path={path} />{mobileNav && <div className="student-mobile-menu-panel"><div className="student-mobile-menu-head"><strong>Student workspace</strong><button onClick={() => setMobileNav(false)} aria-label="Close navigation"><X size={18} /></button></div>{mobileItems.map(([label, target, Icon]) => <button key={target} onClick={() => { setMobileNav(false); go(target) }}><Icon size={17} />{label}</button>)}<button className="student-mobile-new-task" onClick={() => { setMobileNav(false); setStudioOpen(true) }}><Plus size={17} />New Task</button><button onClick={() => go('/login')}><LogOut size={17} />Sign out</button></div>}<main className="student-content">{studioOpen ? <TaskCreationStudio onClose={() => setStudioOpen(false)} onCreated={onCreated} /> : state.loading ? <DashboardSkeleton /> : state.error ? <DashboardError onRetry={load} access={state.error.message === 'STUDENT_ACCESS_REQUIRED'} /> : <><section className="student-dashboard-heading"><p className="student-overline">STUDENT WORKSPACE</p><h1>{model.focusAction ? 'Here’s what needs your attention.' : model.tasks.length ? 'Here’s where things stand.' : 'Start with your assignment brief.'}</h1><p>{model.focusAction ? 'One clear next step keeps your work moving.' : model.tasks.length ? 'Your tasks, progress, and updates are together here.' : 'Upload a brief and let Solvy help you understand it before you commit.'}</p></section><FocusStrip action={model.focusAction} /><ActiveTask task={model.activeTask} onNewTask={() => setStudioOpen(true)} /><div className="student-lower-grid"><TaskList tasks={model.tasks} /><Activity items={model.recentActivity} /></div>{model.upcomingActions.length > 0 && <section className="student-upcoming"><p className="student-overline">UPCOMING</p>{model.upcomingActions.map((item, index) => <button key={item.id || index} onClick={() => item.route && go(item.route)}><time>{formatDate(item.date || item.deadline)}</time><span><strong>{item.title || item.type}</strong><small>{item.taskTitle || item.taskReference || ''}</small></span><ChevronRight size={15} /></button>)}</section>}</>}</main><StudentMobileNav onNewTask={() => setStudioOpen(true)} /></div><AnimatePresence>{notificationsOpen && model && <NotificationDrawer notifications={model.notifications} onClose={() => setNotificationsOpen(false)} />}</AnimatePresence></div>
}
