import { forwardRef, useEffect, useMemo, useRef, useState } from 'react'
import { ArrowRight, Check, ChevronDown, MoreHorizontal, RefreshCw, Search, X } from 'lucide-react'
import { fetchStudentTaskPreview, fetchStudentTasks, filterStudentTasks, formatDate, formatRelativeTime, getTaskJourney, sortStudentTasks, TASK_VIEWS } from '../../student/studentTasksData.js'

const go = (path) => { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')) }
const CLOSED = new Set(['COMPLETED', 'CANCELLED', 'DECLINED'])
const SORT_OPTIONS = [['updated', 'Recently updated'], ['deadline', 'Deadline soonest'], ['newest', 'Newest'], ['title', 'Title A–Z']]
function SortDropdown({ value, onChange }) {
  const [open, setOpen] = useState(false)
  const ref = useRef(null)
  const current = SORT_OPTIONS.find(([key]) => key === value)
  useEffect(() => { const handler = (event) => { if (ref.current && !ref.current.contains(event.target)) setOpen(false) }; document.addEventListener('mousedown', handler); return () => document.removeEventListener('mousedown', handler) }, [])
  return <div className="my-tasks-sort" ref={ref}>
    <span>Sort</span>
    <button className="my-tasks-sort-trigger" onClick={() => setOpen((v) => !v)} aria-expanded={open} aria-haspopup="listbox">
      {current?.[1] || 'Recently updated'}
      <ChevronDown size={14} />
    </button>
    {open && <div className="my-tasks-sort-dropdown" role="listbox">
      {SORT_OPTIONS.map(([key, label]) => <button key={key} role="option" aria-selected={value === key} className={value === key ? 'is-active' : ''} onClick={() => { onChange(key); setOpen(false) }}>{label}{value === key && <Check size={14} />}</button>)}
    </div>}
  </div>
}
function Dot({ tone }) { return <span className={`my-task-dot tone-${tone}`} aria-hidden="true" /> }
function TasksError({ access, retry }) { return <div className="my-tasks-state" role="alert"><p className="student-overline">{access ? 'ACCESS REQUIRED' : 'COULD NOT LOAD TASKS'}</p><h2>{access ? 'Sign in to view your tasks.' : 'We could not load your tasks.'}</h2><p>{access ? 'Your student session is missing or has expired.' : 'We could not retrieve your task ledger.'}</p><button className="my-task-inline-button" onClick={() => access ? go('/login') : retry()}>{access ? 'Sign in' : 'Retry'} <RefreshCw size={14} /></button></div> }
function Skeleton() { return <div className="my-task-skeleton" aria-label="Loading tasks">{Array.from({ length: 6 }, (_, index) => <div key={index}><span /><i /><i /><i /></div>)}</div> }
function PreviewSection({ title, children }) { return <section className="my-task-preview-section"><p className="my-task-eyebrow">{title}</p>{children}</section> }
function TaskPreview({ task, loading, error, access, retry }) {
  if (!task && loading) return <aside className="my-task-preview"><Skeleton /></aside>
  if (!task) return <aside className="my-task-preview my-task-preview--empty"><p>Select a task to see its progress and next step.</p></aside>
  if (error) return <aside className="my-task-preview my-task-preview--empty" role="alert"><p>{access ? 'Sign in to view this task preview.' : 'We could not load this task preview.'}</p><button className="my-task-inline-button" onClick={() => access ? go('/login') : retry()}>{access ? 'Sign in' : 'Retry'} <RefreshCw size={14} /></button></aside>
  const journey = getTaskJourney(task)
  const currentIndex = journey.findIndex((stage) => stage.status === 'current')
  const state = task.display
  return <aside className="my-task-preview" aria-live="polite"><p className="my-task-eyebrow">{state.label.toUpperCase()}</p><h2>{task.title}</h2><p className="my-task-subtitle">{[task.subject, task.reference].filter(Boolean).join(' · ')}</p><button className="my-task-primary" onClick={() => task.nextAction.route && go(task.nextAction.route)}>{task.nextAction.label}<ArrowRight size={15} /></button><PreviewSection title="Journey"><ol className="my-task-journey">{journey.map((stage, index) => <li key={stage.key} className={`is-${stage.status}`}><span>{stage.status === 'complete' ? <Check size={11} /> : String(index + 1).padStart(2, '0')}</span><b>{stage.label}</b>{stage.status === 'current' && <em>Current</em>}</li>)}</ol></PreviewSection><PreviewSection title="Current"><strong>{state.label}</strong><p>{task.latestUpdate?.text || task.latestUpdate || 'No latest update available.'}</p></PreviewSection>{currentIndex >= 0 && currentIndex < journey.length - 1 && !CLOSED.has(state.key) && <PreviewSection title="Next"><strong>{journey[currentIndex + 1].label}</strong><p>{task.nextAction?.label || 'No action required.'}</p></PreviewSection>}{task.quote?.total && <PreviewSection title="Official plan"><strong>{task.quote.total}</strong>{task.quote.deliveryAt && <p>Delivery: {formatDate(task.quote.deliveryAt)}</p>}</PreviewSection>}{task.payment?.amountDue && <PreviewSection title="Payment"><strong>{task.payment.amountDue}</strong>{task.payment.structure && <p>{task.payment.structure}</p>}</PreviewSection>}{task.delivery && <PreviewSection title="Delivery"><strong>{task.delivery.available ? 'Available' : 'Not yet available'}</strong>{task.delivery.fileCount != null && <p>{task.delivery.fileCount} file{task.delivery.fileCount === 1 ? '' : 's'}</p>}</PreviewSection>}{task.deadline && <PreviewSection title="Deadline"><p>{formatDate(task.deadline)}</p></PreviewSection>}{task.expert && <PreviewSection title="Assigned expert"><div className="my-task-expert"><span>{task.expert.name?.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase()}</span><div><strong>{task.expert.name}</strong><p>{task.expert.verified ? 'Verified SolveNest expert' : 'SolveNest expert'}</p></div></div></PreviewSection>}</aside>
}
function TaskMenu({ task }) { const [open, setOpen] = useState(false); const actions = [{ label: 'Open task', route: task.nextAction.route || '/student/tasks' }, task.display.key === 'DELIVERED' && { label: 'Review delivery', route: '/student/deliveries' }].filter(Boolean); return <div className="my-task-menu-wrap"><button className="my-task-menu" aria-label={`Actions for ${task.title}`} aria-expanded={open} onClick={(event) => { event.stopPropagation(); setOpen((value) => !value) }}><MoreHorizontal size={17} /></button>{open && <div className="my-task-menu-popover" role="menu">{actions.map((action) => <button key={action.label} role="menuitem" onClick={(event) => { event.stopPropagation(); setOpen(false); go(action.route) }}>{action.label}</button>)}</div>}</div> }
const TaskRow = forwardRef(function TaskRow({ task, selected, tabIndex, select, onKeyDown }, ref) { return <div ref={ref} className={`my-task-row ${selected ? 'is-selected' : ''}`} role="row" tabIndex={tabIndex} aria-selected={selected} onClick={() => select(task)} onKeyDown={(event) => onKeyDown(event, task)}><div className="my-task-row-title"><Dot tone={task.display.tone} /><div><strong>{task.title}</strong><small>{[task.subject, task.reference].filter(Boolean).join(' · ') || 'Task'}</small></div></div><div className="my-task-row-stage"><Dot tone={task.display.tone} />{task.display.label}</div><div className="my-task-row-deadline">{formatDate(task.deadline)}</div><div className="my-task-row-updated">{formatRelativeTime(task.updatedAt || task.latestUpdate?.createdAt)}</div><button className="my-task-row-action my-task-row-action-button" onClick={(event) => { event.stopPropagation(); if (task.nextAction.route) go(task.nextAction.route) }}>{task.nextAction.needsStudentAction ? task.nextAction.label : 'No action needed'}</button><TaskMenu task={task} /></div> })

export function StudentTasksPage() {
  const [state, setState] = useState({ loading: true, loadingMore: false, error: null, tasks: [], meta: null })
  const params = new URLSearchParams(window.location.search)
  const [search, setSearch] = useState(params.get('q') || '')
  const [view, setView] = useState(params.get('view') || 'all')
  const [sort, setSort] = useState(params.get('sort') || 'updated')
  const [selectedId, setSelectedId] = useState(params.get('task'))
  const [preview, setPreview] = useState(null)
  const [previewLoading, setPreviewLoading] = useState(false)
  const [previewError, setPreviewError] = useState(null)
  const rows = useRef([])
  const previewRequest = useRef(null)
  const load = (page = 1, append = false) => { const controller = new AbortController(); setState((current) => ({ ...current, loading: !append, loadingMore: append, error: null })); fetchStudentTasks({ page, signal: controller.signal }).then(({ tasks, meta }) => setState((current) => ({ loading: false, loadingMore: false, error: null, tasks: append ? [...current.tasks, ...tasks] : tasks, meta }))).catch((error) => { if (error.name !== 'AbortError') setState((current) => ({ ...current, loading: false, loadingMore: false, error })) }); return () => controller.abort() }
  useEffect(() => load(), [])
  const tasks = useMemo(() => sortStudentTasks(filterStudentTasks(state.tasks, { search, view }), sort), [state.tasks, search, view, sort])
  const selected = tasks.find((task) => String(task.id) === String(selectedId)) || null
  const select = (task) => { previewRequest.current?.abort(); const controller = new AbortController(); previewRequest.current = controller; setSelectedId(String(task.id)); setPreview(task); setPreviewError(null); setPreviewLoading(true); fetchStudentTaskPreview(task.id, { signal: controller.signal }).then((result) => !controller.signal.aborted && setPreview(result)).catch((error) => { if (!controller.signal.aborted) { setPreviewError(error); setPreview(task) } }).finally(() => !controller.signal.aborted && setPreviewLoading(false)) }
  useEffect(() => { if (selected && !preview && window.innerWidth >= 1024) select(selected); else if (!selected && tasks[0] && window.innerWidth >= 1024) select(tasks[0]) }, [selected?.id, tasks.length])
  useEffect(() => { const next = new URLSearchParams(); if (search) next.set('q', search); if (view !== 'all') next.set('view', view); if (sort !== 'updated') next.set('sort', sort); if (selectedId) next.set('task', selectedId); window.history.replaceState({}, '', `${window.location.pathname}${next.toString() ? `?${next}` : ''}`) }, [search, view, sort, selectedId])
  const keyboard = (event, task) => { const index = tasks.findIndex((item) => item.id === task.id); if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); const next = Math.max(0, Math.min(tasks.length - 1, index + (event.key === 'ArrowDown' ? 1 : -1))); rows.current[next]?.focus(); select(tasks[next]) } if (event.key === 'ArrowRight') { event.preventDefault(); rows.current[index]?.querySelector('.my-task-menu')?.focus() } if (event.key === 'Enter') { event.preventDefault(); if (task.nextAction.route) go(task.nextAction.route) } }
  const activeCount = state.tasks.filter((task) => !CLOSED.has(task.display.key)).length
  const needsCount = state.tasks.filter((task) => task.display.needsStudentAction).length
  const hasMore = state.meta?.hasMore || state.meta?.current_page < state.meta?.last_page
  const content = state.loading ? <Skeleton /> : state.error ? <TasksError access={state.error.message === 'STUDENT_ACCESS_REQUIRED'} retry={() => load()} /> : tasks.length === 0 ? <div className="my-tasks-state"><p className="student-overline">{search ? 'NO MATCHING TASKS' : 'NO TASKS IN THIS VIEW'}</p><h2>{search ? 'Nothing matches that search.' : 'No tasks here yet.'}</h2><p>{search ? 'Try another title, subject, or reference.' : 'Tasks will appear here as your workspace changes.'}</p>{search && <button className="my-task-inline-button" onClick={() => setSearch('')}>Clear search <X size={14} /></button>}</div> : <div className="my-tasks-layout"><div className="my-tasks-ledger" role="grid" aria-label="Your tasks">{tasks.map((task, index) => <TaskRow key={task.id} task={task} selected={String(task.id) === String(selectedId)} tabIndex={index === 0 ? 0 : -1} select={select} onKeyDown={keyboard} ref={(element) => { rows.current[index] = element }} />)}{hasMore && <button className="my-task-load-more" onClick={() => load((state.meta.current_page || 1) + 1, true)} disabled={state.loadingMore}>{state.loadingMore ? 'Loading…' : 'Load more'}</button>}</div><TaskPreview task={preview || selected} loading={previewLoading} error={previewError} access={previewError?.message === 'STUDENT_ACCESS_REQUIRED'} retry={() => selected && select(selected)} /></div>
  return <div className="my-tasks-page"><header className="my-tasks-header"><div><p className="student-overline">STUDENT WORKSPACE</p><h1>My Tasks</h1><p>Track what needs you, what is moving, and what is complete.</p></div><span className="my-tasks-count"><strong>{activeCount}</strong><small>active task{activeCount === 1 ? '' : 's'}</small></span></header><div className="my-tasks-controls"><div className="my-tasks-controls-top"><label className="my-tasks-search"><Search size={16} /><span className="sr-only">Search tasks</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search tasks…" />{search && <button onClick={() => setSearch('')} aria-label="Clear search"><X size={14} /></button>}</label><SortDropdown value={sort} onChange={setSort} /></div><div className="my-tasks-views" role="tablist" aria-label="Task views">{TASK_VIEWS.map(([key, label]) => <button key={key} role="tab" aria-selected={view === key} className={view === key ? 'is-active' : ''} onClick={() => setView(key)}>{label}{key === 'needs-you' && needsCount > 0 && <span>{needsCount}</span>}</button>)}</div></div>{content}</div>
}
