import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, FileText, LoaderCircle, Plus, RefreshCw, Sparkles, Trash2, UploadCloud, X } from 'lucide-react'
import { AnimatePresence, motion } from 'framer-motion'
import { createStudentTask, analyzeStudentTask, uploadStudentTaskFile } from '../../student/studentTaskCreation.js'

const STEPS = [['upload', 'Upload'], ['analyze', 'Understand'], ['review', 'Review'], ['create', 'Create']]
const ACCEPTED = '.pdf,.docx,.pptx,.jpg,.jpeg,.png'
const MAX_TOTAL_BYTES = 100 * 1024 * 1024
const fmt = (bytes) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`
const ext = (name) => (name.split('.').pop() || '').toUpperCase()

function StudioNotice({ tone = 'info', title, children, action }) { return <div className={`studio-notice is-${tone}`} role={tone === 'error' ? 'alert' : 'status'}><span className="studio-notice-mark" /><div><strong>{title}</strong>{children && <p>{children}</p>}</div>{action}</div> }
function Button({ children, onClick, secondary = false, disabled = false, loading = false, type = 'button' }) { return <button type={type} disabled={disabled || loading} className={secondary ? 'student-button student-button--secondary' : 'student-button'} onClick={onClick}>{loading ? <><LoaderCircle className="studio-spin" size={15} />{children}</> : children}<ArrowRight size={15} /></button> }
function FileRow({ file, onRemove, onRetry }) { return <div className="studio-file-row"><span className="studio-file-icon"><FileText size={16} /></span><span className="studio-file-details"><strong>{file.name}</strong><small>{ext(file.name)} · {fmt(file.size)} {file.status === 'uploading' ? `· ${file.progress || 0}%` : ''}</small></span>{file.status === 'uploading' && <span className="studio-file-progress"><i style={{ width: `${file.progress || 0}%` }} /></span>}{file.status === 'ready' && <Check className="studio-file-ready" size={16} />}{file.status === 'error' && <><button className="studio-inline-action" onClick={() => onRetry(file)}><RefreshCw size={14} />Retry</button><span className="studio-file-error">Upload failed</span></>}{file.status !== 'uploading' && <button className="studio-remove-file" onClick={() => onRemove(file)} aria-label={`Remove ${file.name}`}><Trash2 size={15} /></button>}</div> }

function UploadStep({ files, onFiles, onRemove, onRetry, error }) {
  const inputRef = useRef(null)
  const brief = files.find((file) => file.kind === 'brief')
  const supporting = files.filter((file) => file.kind !== 'brief')
  return <div className="studio-upload-step"><div className="studio-step-intro"><div><p className="student-overline">01 / UPLOAD</p><h2>Upload your task</h2><p>Add the assignment brief first. You can include a rubric or supporting material too.</p></div><span className="studio-solvy-mark"><Sparkles size={14} /> SOLVY</span></div><input ref={inputRef} className="studio-hidden-input" type="file" accept={ACCEPTED} multiple tabIndex="-1" aria-hidden="true" onChange={(event) => { onFiles(Array.from(event.target.files || [])); event.target.value = '' }} /><button className={`studio-dropzone ${brief ? 'has-file' : ''}`} onClick={() => inputRef.current?.click()} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); onFiles(Array.from(event.dataTransfer.files || [])) }}><UploadCloud size={24} /><strong>{brief ? 'Replace or add files' : 'Add assignment brief'}</strong><span>PDF, DOCX, PPTX or image files · 100 MB total</span></button>{error && <StudioNotice tone="error" title="Upload failed">{error}</StudioNotice>}<div className="studio-file-section"><div className="studio-file-section-head"><div><p className="student-overline">MAIN BRIEF</p><small>The primary assignment instructions.</small></div>{brief && <button className="studio-add-button" onClick={() => inputRef.current?.click()}><Plus size={14} />Replace</button>}</div>{brief ? <FileRow file={brief} onRemove={onRemove} onRetry={onRetry} /> : <p className="studio-empty-file">Your assignment brief will appear here.</p>}</div><div className="studio-file-section"><div className="studio-file-section-head"><div><p className="student-overline">SUPPORTING FILES</p><small>Rubric, references, or other material.</small></div><button className="studio-add-button" onClick={() => inputRef.current?.click()}><Plus size={14} />Add</button></div>{supporting.length ? supporting.map((file) => <FileRow key={file.id} file={file} onRemove={onRemove} onRetry={onRetry} />) : <p className="studio-empty-file">No supporting files added.</p>}</div></div>
}
function AnalysisStep({ analysis, loading, error, onRetry }) { return <div className="studio-analysis-step"><div className="studio-step-intro"><div><p className="student-overline">02 / UNDERSTAND</p><h2>{loading ? 'Solvy is reading your task…' : 'Solvy understood this'}</h2><p>{loading ? 'We are waiting for the actual analysis response.' : 'Review the information returned by the analysis service before creating your task.'}</p></div><span className="studio-solvy-mark"><Sparkles size={14} /> SOLVY</span></div>{loading && <div className="studio-analysis-loading"><LoaderCircle className="studio-spin" size={20} /><span>Reading your uploaded brief…</span></div>}{error && <StudioNotice tone="error" title="Analysis failed" action={<button className="studio-inline-action" onClick={onRetry}>Retry</button>}>{error}</StudioNotice>}{!loading && !error && analysis && <div className="studio-analysis-grid">{Object.entries(analysis).filter(([, value]) => value !== null && value !== undefined && value !== '').map(([key, value]) => <div className="studio-analysis-field" key={key}><small>{key.replace(/([A-Z])/g, ' $1')}</small><strong>{Array.isArray(value) ? value.join(', ') : String(value)}</strong><span>Returned by Solvy</span></div>)}</div>}{!loading && !error && !analysis && <p className="studio-empty-file">Analysis results will appear here after you analyze the brief.</p>}</div> }
function ReviewStep({ files, analysis }) { return <div className="studio-review-step"><div className="studio-step-intro"><div><p className="student-overline">03 / REVIEW</p><h2>Check the task details</h2><p>Confirm the returned information before creating your task.</p></div></div><div className="studio-review-list"><div><span>Primary brief</span><strong>{files.find((file) => file.kind === 'brief')?.name || 'Not uploaded'}</strong></div>{analysis && Object.entries(analysis).filter(([, value]) => value !== null && value !== undefined && value !== '').map(([key, value]) => <div key={key}><span>{key.replace(/([A-Z])/g, ' $1')}</span><strong>{Array.isArray(value) ? value.join(', ') : String(value)}</strong></div>)}</div></div> }
function SuccessStep({ createdTask, onView, onClose }) { return <motion.div className="studio-success" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}><span className="studio-success-mark"><Check size={22} /></span><p className="student-overline">TASK CREATED</p><h2>Your task has been added to your workspace.</h2><p>{createdTask?.status ? `Current state: ${createdTask.status}.` : 'The backend returned the new task.'}</p><div><Button onClick={onView}>View task</Button><Button secondary onClick={onClose}>Back to dashboard</Button></div></motion.div> }

export function TaskCreationStudio({ onClose, onCreated }) {
  const [step, setStep] = useState('upload')
  const [files, setFiles] = useState([])
  const [analysis, setAnalysis] = useState(null)
  const [analysisError, setAnalysisError] = useState(null)
  const [uploadError, setUploadError] = useState(null)
  const [loadingAnalysis, setLoadingAnalysis] = useState(false)
  const [creating, setCreating] = useState(false)
  const [createdTask, setCreatedTask] = useState(null)
  const [closePrompt, setClosePrompt] = useState(false)
  const dirty = files.length > 0 || analysis !== null
  const brief = files.find((file) => file.kind === 'brief')
  const addFiles = async (incoming) => {
    setUploadError(null)
    const total = files.reduce((sum, file) => sum + file.size, 0) + incoming.reduce((sum, file) => sum + file.size, 0)
    if (total > MAX_TOTAL_BYTES) { setUploadError('These files exceed the 100 MB total limit.'); return }
    const next = []
    for (const file of incoming) {
      const kind = files.some((item) => item.kind === 'brief') || next.some((item) => item.kind === 'brief') ? 'supporting' : 'brief'
      const draft = { id: `${file.name}-${file.lastModified}`, name: file.name, size: file.size, kind, status: 'uploading', progress: 0, raw: file }
      next.push(draft); setFiles((current) => [...current, draft])
      try { await uploadStudentTaskFile(file, kind, (progress) => setFiles((current) => current.map((item) => item.id === draft.id ? { ...item, progress } : item))); setFiles((current) => current.map((item) => item.id === draft.id ? { ...item, status: 'ready', progress: 100 } : item)) } catch (error) { setFiles((current) => current.map((item) => item.id === draft.id ? { ...item, status: 'error', error: error.message } : item)); setUploadError(error.message || 'Upload failed. Please try again.') }
    }
  }
  const removeFile = (file) => setFiles((current) => current.filter((item) => item.id !== file.id))
  const retryFile = (file) => { removeFile(file); addFiles([file.raw]) }
  const runAnalysis = async () => { if (!brief || brief.status !== 'ready') return; setLoadingAnalysis(true); setAnalysisError(null); setStep('analyze'); try { const result = await analyzeStudentTask(files.map((file) => file.id)); setAnalysis(result.analysis || result); setStep('review') } catch (error) { setAnalysisError(error.message || 'Analysis failed. Please try again.') } finally { setLoadingAnalysis(false) } }
  const createTask = async () => { if (!brief || creating) return; setCreating(true); try { const result = await createStudentTask({ fileIds: files.map((file) => file.id), analysis }); setCreatedTask(result.task || result); setStep('create'); onCreated?.(result) } catch (error) { setAnalysisError(error.message || 'Task creation failed. Please try again.') } finally { setCreating(false) } }
  useEffect(() => () => files.forEach((file) => { if (file.raw) URL.revokeObjectURL(file.raw) }), [])
  if (createdTask) return <div className="studio-shell"><StudioHeader onClose={() => onClose()} /><SuccessStep createdTask={createdTask} onView={() => go(`/student/tasks/${createdTask.id || ''}`)} onClose={onClose} /></div>
  return <div className="studio-shell"><StudioHeader onClose={() => dirty ? setClosePrompt(true) : onClose()} /><div className="studio-progress" aria-label="Task creation progress">{STEPS.map(([key, label], index) => <div className={`studio-progress-step is-${STEPS.findIndex(([name]) => name === step) > index ? 'complete' : key === step ? 'current' : 'future'}`} key={key}><span>{String(index + 1).padStart(2, '0')}</span><b>{label}</b>{index < STEPS.length - 1 && <i />}</div>)}</div><AnimatePresence mode="wait"><motion.div key={step} className="studio-content" initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -10 }} transition={{ duration: .28 }}>{step === 'upload' && <UploadStep files={files} onFiles={addFiles} onRemove={removeFile} onRetry={retryFile} error={uploadError} />}{step === 'analyze' && <AnalysisStep analysis={analysis} loading={loadingAnalysis} error={analysisError} onRetry={runAnalysis} />}{step === 'review' && <ReviewStep files={files} analysis={analysis} />}</motion.div></AnimatePresence><div className="studio-footer"><Button secondary onClick={() => step === 'upload' ? (dirty ? setClosePrompt(true) : onClose()) : setStep(STEPS[Math.max(0, STEPS.findIndex(([key]) => key === step) - 1)][0])}><ArrowLeft size={15} />{step === 'upload' ? 'Close' : 'Back'}</Button>{step === 'upload' && <Button disabled={!brief || brief.status !== 'ready'} onClick={runAnalysis}>Analyze task</Button>}{step === 'review' && <Button loading={creating} onClick={createTask}>Creating Task…</Button>}</div>{closePrompt && <ConfirmDialog onKeep={() => setClosePrompt(false)} onLeave={onClose} />}</div>
}
function StudioHeader({ onClose }) { return <div className="studio-header"><div><p className="student-overline">DASHBOARD / NEW TASK</p><h1>Start with the brief.</h1><p>Upload the task instructions and Solvy will help structure what comes next.</p></div><button className="student-icon-button" onClick={onClose} aria-label="Close task studio"><X size={19} /></button></div> }
function ConfirmDialog({ onKeep, onLeave }) { return <div className="studio-dialog-backdrop"><section className="studio-dialog" role="dialog" aria-modal="true" aria-labelledby="leave-title"><p className="student-overline">LEAVE TASK SETUP?</p><h2 id="leave-title">Your uploaded files or details may not be saved.</h2><p>Continue editing or leave this setup.</p><div><Button secondary onClick={onKeep}>Continue editing</Button><button className="studio-danger-button" onClick={onLeave}>Leave setup</button></div></section></div> }
function go(path) { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')) }
