import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowUpRight, Menu, X } from 'lucide-react'
import { AnalyzePage, ConnectPage, HelpPage, WhyPage } from '../pages/Premium/PremiumPages.jsx'
import { WhySolveNestPage } from '../pages/Why/WhySolveNestPage.jsx'
import { HelpCentrePage } from '../pages/Help/HelpCentrePage.jsx'
import { PlansPage } from '../pages/Plans/PlansPage.jsx'
import { MethodPage } from '../pages/Method/MethodPage.jsx'
import { DomainsPage } from '../pages/Domains/StudyDomainsPage.jsx'
import { InteractiveConnectPage, InteractiveHelpPage, InteractivePlansPage } from '../pages/Premium/InteractivePages.jsx'
import { PremiumLoginPage, PremiumRegisterPage } from '../pages/Auth/AuthPages.jsx'
import { AcademicAurora, MagneticButton } from '../components/common/GlobalExperience.jsx'
import { FocusedHomePage } from '../pages/Home/FocusedHomePage.jsx'
import logoImg from '../assets/logo-bg-removed.png'

const links = [['The SolveNest Method', '/method'], ['Study Domains', '/domains'], ['Plans & Estimates', '/plans'], ['Why SolveNest', '/why-solvenest'], ['Help Centre', '/help'], ['Connect', '/connect']]
const navigate = (path) => { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')) }

function Header({ menuOpen, setMenuOpen, path }) {
  const [scrolled, setScrolled] = useState(false)
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 90); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll) }, [])
    return <><motion.header layout className={scrolled ? 'topbar is-scrolled' : 'topbar'} transition={{ layout: { duration: .45, ease: [0.22, 1, .36, 1] } }}><button className="brand" onClick={() => navigate('/')}><span className="brand-logo-frame"><img className="brand-logo" src={logoImg} alt="SolveNest logo" /></span><span>SolveNest</span></button><nav className={menuOpen ? 'main-nav is-open' : 'main-nav'}>{links.map(([label, target]) => <button className={path === target ? 'active' : ''} key={target} onClick={() => { navigate(target); setMenuOpen(false) }}>{label}</button>)}</nav><div className="header-actions"><button className="text-button" onClick={() => navigate('/login')}>Sign in</button><MagneticButton className="dark-button" onClick={() => navigate('/analyze')}>Analyze my task <ArrowUpRight size={16} /></MagneticButton></div><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button></motion.header><AnimatePresence>{menuOpen && <motion.div className="mobile-command-panel" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><span className="mobile-panel-label">SOLVENEST / NAVIGATION PATH</span>{links.map(([label, target], index) => <motion.button initial={{ opacity: 0, x: -15 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .06 }} key={target} onClick={() => { navigate(target); setMenuOpen(false) }}><span>0{index + 1}</span><b>{label}</b><ArrowUpRight size={17} /></motion.button>)}<MagneticButton className="mobile-analyze" onClick={() => { navigate('/analyze'); setMenuOpen(false) }}>Analyze my task <ArrowUpRight size={17} /></MagneticButton></motion.div>}</AnimatePresence></>
}
function Footer() { return <footer><div><button className="brand" onClick={() => navigate('/')}><span className="brand-logo-frame"><img className="brand-logo" src={logoImg} alt="SolveNest logo" /></span><span>SolveNest</span></button><p>Premium academic intelligence + human expertise.</p></div><div className="footer-links"><span>Platform</span><button onClick={() => navigate('/method')}>The method</button><button onClick={() => navigate('/analyze')}>Analyze a task</button></div><div className="footer-links"><span>Trust</span><button onClick={() => navigate('/why-solvenest')}>Why SolveNest</button><button onClick={() => navigate('/help')}>Help centre</button></div><div className="footer-links"><span>Legal</span><button>Privacy</button><button>Academic integrity</button></div><div className="footer-wordmark">SOLVENEST</div></footer> }

export function App() { const [path, setPath] = useState(window.location.pathname); const [menuOpen, setMenuOpen] = useState(false); const [transitioning, setTransitioning] = useState(false); useEffect(() => { const update = () => { setTransitioning(true); setPath(window.location.pathname); setMenuOpen(false); window.scrollTo(0, 0); window.setTimeout(() => setTransitioning(false), 600) }; window.addEventListener('popstate', update); return () => window.removeEventListener('popstate', update) }, []); const Page = { '/': FocusedHomePage, '/method': MethodPage, '/domains': DomainsPage, '/plans': PlansPage, '/why-solvenest': WhySolveNestPage, '/help': HelpCentrePage, '/connect': InteractiveConnectPage, '/analyze': AnalyzePage, '/submit': AnalyzePage, '/login': PremiumLoginPage, '/register': PremiumRegisterPage, '/how-it-works': MethodPage, '/categories': DomainsPage, '/pricing': PlansPage, '/about': WhyPage, '/faq': InteractiveHelpPage, '/contact': InteractiveConnectPage }[path] || FocusedHomePage; return <div className="site-shell"><AcademicAurora /><Header path={path} menuOpen={menuOpen} setMenuOpen={setMenuOpen} /><main><AnimatePresence mode="wait"><motion.div key={path} initial={{ opacity: 0, scale: .985, filter: 'blur(5px)' }} animate={{ opacity: 1, scale: 1, filter: 'blur(0px)' }} exit={{ opacity: 0, scale: .985, filter: 'blur(4px)' }} transition={{ duration: .55, ease: [0.22, 1, .36, 1] }}><Page /></motion.div></AnimatePresence></main><Footer /><div className={transitioning ? 'route-transition is-running' : 'route-transition'} aria-hidden="true" /></div> }
