import { useEffect, useRef, useState } from 'react'
import { AnimatePresence, motion, useScroll, useSpring, useTransform } from 'framer-motion'
import { ArrowRight, CalendarDays, Check, FileCheck2, FileText, LockKeyhole, ScanLine, ShieldCheck, Sparkles, Users } from 'lucide-react'
import { MagneticButton } from '../../components/common/GlobalExperience.jsx'
import { routeTo } from '../Premium/PremiumPages.jsx'

const stages = [['UNDERSTAND', 'See how Solvy turns the brief into structure.'], ['CONFIRM', 'Human review turns an estimate into approved scope.'], ['PROGRESS', 'Track the work through one clear workspace.']]
const fields = [['words', 'Word count', '2,500 words'], ['citation', 'Referencing', 'APA 7'], ['deadline', 'Deadline', '5 days'], ['rubric', 'Rubric', '6 criteria']]

function CTA({ children = 'Analyze My Task' }) { return <MagneticButton className="fh-cta" onClick={() => routeTo('/analyze')}>{children}<ArrowRight size={17} /></MagneticButton> }
function Paper({ compact = false, highlight = '' }) { return <div className={compact ? 'fh-paper compact' : 'fh-paper'}><div className="fh-paper-bar"><span>SOLVENEST / BRIEF 0247</span><span>ASSESSMENT 2</span></div><span className="fh-paper-kicker">RESEARCH REPORT</span><h3>Urban resilience<br /><em>in changing cities</em></h3><div className="fh-paper-fields">{[['words', 'WORD COUNT', '2,500 words'], ['deadline', 'DUE', '28 September'], ['citation', 'REFERENCING', 'APA 7']].map(([key, label, value]) => <div className={highlight === key ? 'active' : ''} key={key}><small>{label}</small><b>{value}</b></div>)}</div><div className="fh-paper-copy"><b>Overview</b><p>Evaluate how cities can adapt to climate pressure using current research.</p><b>Requirements</b><p>Compare two urban approaches and support the discussion with evidence.</p></div><div className={highlight === 'rubric' ? 'fh-rubric active' : 'fh-rubric'}><b>Rubric / 6 criteria</b><div>{Array.from({ length: 12 }, (_, i) => <i key={i} />)}</div></div><div className="fh-paper-footer"><span>Assessment weighting: 30%</span><span>01 / 04</span></div></div> }
function Summary({ focus, setFocus }) { return <div className="fh-summary"><div className="fh-summary-head"><span><i /> SOLVY TASK SUMMARY</span><small>STRUCTURED</small></div><h3>Research Report</h3>{fields.map(([key, label, value]) => <button className={focus === key ? 'active' : ''} key={key} onMouseEnter={() => setFocus(key)} onFocus={() => setFocus(key)}><span>{label}</span><b>{value}</b><ArrowRight size={14} /></button>)}<div className="fh-summary-range"><small>ESTIMATED RANGE</small><strong>LKR 8,000 – 10,000</strong><span>Approximate, not a binding quote</span></div></div> }
function Hero() { const ref = useRef(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start start', 'end start'] }); const progress = useSpring(scrollYProgress, { stiffness: 80, damping: 22 }); const copyY = useTransform(progress, [0, 1], [0, -45]); const visualY = useTransform(progress, [0, 1], [0, 20]); const [focus, setFocus] = useState('words'); useEffect(() => { const cycle = ['words', 'citation', 'deadline', 'rubric']; let index = 0; const timer = window.setInterval(() => { index = (index + 1) % cycle.length; setFocus(cycle[index]) }, 2200); return () => window.clearInterval(timer) }, []); return <section ref={ref} className="focused-hero"><div className="fh-grid-bg" /><motion.div className="fh-hero-copy" style={{ y: copyY }}><span className="fh-eyebrow"><i /> AI-assisted analysis <b>•</b> Human-confirmed decisions</span><h1>Understand your<br />assignment <em>before<br />you commit.</em></h1><p>Upload your academic brief and let Solvy identify the requirements, complexity, missing information and estimated support range — before you create an account.</p><div className="fh-actions"><CTA /><button className="fh-secondary" onClick={() => routeTo('/method')}>Watch Solvy Analyze <ArrowRight size={16} /></button></div><div className="fh-trust"><span><Check size={13} /> No account required to begin</span><span><LockKeyhole size={13} /> Private processing</span><span><ShieldCheck size={13} /> Human-confirmed final quote</span></div></motion.div><motion.div className="fh-hero-visual" style={{ y: visualY }}><div className="fh-visual-label">ASSIGNMENT INTELLIGENCE PREVIEW <b>LIVE</b></div><div className="fh-document-summary"><div className="fh-document-wrap"><Paper highlight={focus} /><span className="fh-scanner" /></div><Summary focus={focus} setFocus={setFocus} /></div><div className="fh-visual-foot"><span><i /> Solvy is reading the brief</span><span>DOCUMENT → ANALYSIS → STRUCTURE</span></div></motion.div></section> }
function TrustStrip() { const items = [['Analyze before signup', ScanLine], ['Human-confirmed pricing', Users], ['Controlled expert network', ShieldCheck], ['Quality review before delivery', FileCheck2]]; return <section className="fh-trust-strip"><div className="fh-container">{items.map(([label, Icon], i) => <motion.div key={label} initial={{ opacity: 0, x: -12 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: i * .1 }}><Icon size={17} /><span>{label}</span></motion.div>)}</div></section> }
function UnderstandStage() { const [focus, setFocus] = useState('words'); return <div className="journey-understand"><div className="journey-paper"><Paper highlight={focus} /></div><div className="journey-analysis"><span className="workspace-label">STRUCTURED INTERPRETATION</span>{fields.map(([key, label, value]) => <button className={focus === key ? 'active' : ''} key={key} onMouseEnter={() => setFocus(key)} onFocus={() => setFocus(key)}><span>{label}</span><b>{value}</b><ArrowRight size={14} /></button>)}</div></div> }
function ConfirmStage() { return <div className="journey-confirm"><div className="estimate-block"><span className="workspace-label">SOLVY ESTIMATE</span><strong>LKR 8,000 – 10,000</strong><small>Complexity · Medium<br />Suggested delivery · 5 days</small></div><div className="confirm-path"><span>AI suggestion</span><i /><ArrowRight size={20} /><span>Human review</span><i /><ArrowRight size={20} /><span className="confirmed">Confirmed</span></div><div className="official-block"><span className="workspace-label">OFFICIAL SOLVENEST PLAN</span><strong>LKR 8,750</strong><small>Delivery · 5 days<br />Included scope · Confirmed<br />Revisions · 2</small></div></div> }
function ProgressStage() { return <div className="journey-progress"><div className="task-title"><span className="workspace-label">TASK ROOM PREVIEW</span><h3>Machine Learning Research Project</h3><span className="progress-status"><i /> IN PROGRESS</span></div><div className="mini-rail"><i />{['Paid', 'Expert Assigned', 'In Progress', 'Quality Review', 'Delivered'].map((item, i) => <span className={i < 3 ? 'done' : ''} key={item}><b>{i < 3 ? <Check size={10} /> : ''}</b>{item}</span>)}</div><div className="progress-columns"><div><span className="workspace-label">CURRENT ACTIVITY</span><b>Expert working on:</b><strong>Data Analysis</strong></div><div><span className="workspace-label">RECENT UPDATE</span><b>Requirements confirmed</b><strong>Draft review scheduled</strong></div><div><span className="workspace-label">NEXT STEP</span><b>Internal quality review</b><strong>Expected after draft</strong></div></div></div> }
function Journey() { const [active, setActive] = useState(0); const [userInteracted, setUserInteracted] = useState(false); const ref = useRef(null); const scroll = useScroll({ target: ref, offset: ['start end', 'end start'] }); useEffect(() => { if (userInteracted) return; const timer = window.setInterval(() => setActive((current) => (current + 1) % 3), 6500); return () => window.clearInterval(timer) }, [userInteracted]); useEffect(() => { const unsubscribe = scroll.scrollYProgress.on('change', (value) => { if (userInteracted) return; if (value > .72) setActive(2); else if (value > .42) setActive(1); else if (value > .18) setActive(0) }); return unsubscribe }, [scroll.scrollYProgress, userInteracted]); return <section ref={ref} className="fh-journey"><div className="fh-container"><div className="fh-section-head"><div><span className="fh-label">02 / The SolveNest Journey</span><h2>A clear path from<br /><em>brief to progress.</em></h2></div><p>See the journey at a glance. Explore the full process inside The SolveNest Method.</p></div><div className="journey-showcase"><div className="journey-selector">{stages.map(([title, description], i) => <button className={active === i ? 'active' : ''} key={title} onClick={() => { setActive(i); setUserInteracted(true) }}><span>{String(i + 1).padStart(2, '0')}</span><div><b>{title}</b>{active === i && <small>{description}</small>}</div><i>{active === i ? <Check size={12} /> : ''}</i></button>)}<div className="journey-controls"><button aria-label="Previous stage" onClick={() => { setActive((active + 2) % 3); setUserInteracted(true) }}>←</button><button aria-label="Next stage" onClick={() => { setActive((active + 1) % 3); setUserInteracted(true) }}>→</button></div></div><div className="journey-workspace"><div className="workspace-top"><span>SOLVENEST / ONE TASK, ONE PATH</span><span>{String(active + 1).padStart(2, '0')} / 03</span></div><AnimatePresence mode="wait"><motion.div key={active} className="journey-stage" initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 1.02 }} transition={{ duration: .38 }}>{active === 0 ? <UnderstandStage /> : active === 1 ? <ConfirmStage /> : <ProgressStage />}</motion.div></AnimatePresence></div></div><button className="fh-text-link" onClick={() => routeTo('/method')}>Want to see the complete journey? Explore The SolveNest Method <ArrowRight size={15} /></button></div></section> }
function FinalCTA() { return <section className="fh-final"><div className="fh-final-copy fh-container"><div><span className="fh-label">03 / Start with clarity</span><h2>Upload the brief.<br /><em>Understand the path.</em></h2><p>Receive an initial Solvy analysis before you decide whether to continue with SolveNest.</p><CTA /><small>No account required to begin.</small></div><div className="fh-final-paper"><Paper compact /><div className="fh-final-annotation"><span>Requirements detected</span><span>Rubric found</span><span>Deadline identified</span></div><div className="fh-final-flow" /></div></div></section> }
export function FocusedHomePage() { return <><Hero /><TrustStrip /><Journey /><FinalCTA /></> }
