import { useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowUpRight, Check, ChevronDown, CircleHelp, FileText, ShieldCheck, Sparkles } from 'lucide-react'

const categories = ['Research & writing', 'Design & presentation', 'Code & debugging', 'Review & feedback']
const faqs = [['Is SolveNest a tutoring service?', 'It is a managed academic support platform. Our experts guide, review, and help you improve your work within a clear academic-integrity policy.'], ['How do I know the price before starting?', 'Every request is reviewed before payment. You receive a transparent quote and delivery plan, then decide whether to accept it.'], ['Can I submit a file or a brief?', 'Yes. Share your brief and supporting files securely. Our intake process helps turn a rough request into a clear plan.']]
const go = (path) => window.location.assign(path)

export function Orb() { return <div className="orb-stage" aria-label="Solvy visual companion"><div className="orb-grid" /><div className="orb-line line-a" /><div className="orb-line line-b" /><motion.div className="orb" animate={{ rotate: [0, 8, -5, 0], y: [0, -10, 0] }} transition={{ duration: 8, repeat: Infinity, ease: 'easeInOut' }}><div className="orb-shine" /><div className="orb-eye eye-left" /><div className="orb-eye eye-right" /><div className="orb-smile" /></motion.div><motion.div className="orb-panel panel-analysis" animate={{ y: [0, -7, 0] }} transition={{ duration: 4.5, repeat: Infinity, ease: 'easeInOut' }}><span className="panel-icon">↗</span><span><b>Task analysed</b><small>Research · Medium effort</small></span><i className="panel-check">✓</i></motion.div><motion.div className="orb-panel panel-quote" animate={{ y: [0, 8, 0] }} transition={{ duration: 5.5, repeat: Infinity, ease: 'easeInOut', delay: .6 }}><small>ESTIMATED RANGE</small><b>LKR 8,500 — 12,000</b><div className="mini-bar"><i /></div></motion.div><motion.div className="orb-panel panel-review" animate={{ y: [0, -5, 0] }} transition={{ duration: 6, repeat: Infinity, ease: 'easeInOut', delay: 1 }}><span className="pulse" /> Quality review</motion.div><div className="orb-label"><span className="pulse" /> Solvy is ready to listen</div></div> }
const CTA = ({ children = 'Start a request' }) => <button className="lime-button" onClick={() => go('/submit')}>{children} <ArrowUpRight size={17} /></button>

export function HomePage() { return <><section className="hero section-pad"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Academic support, with a better way</div><h1>Turn the<br /><em>stuck</em> part<br />into <span>progress.</span></h1><p className="hero-lede">Thoughtful, accountable support for the work that matters. Bring us the question, the brief, or the messy middle. We’ll help you find the next clear step.</p><div className="hero-cta"><CTA>Share your challenge</CTA><button className="play-button" onClick={() => go('/how-it-works')}><span>▶</span> See how it works</button></div><div className="trust-line"><div className="avatar-stack"><i>AK</i><i>NM</i><i>RJ</i></div><span>Trusted by students who care about doing good work</span></div></div><Orb /></section><section className="signal-strip"><div>For school, university & early-career work</div><div className="strip-line" /><div>Clear plans · Human oversight · No guesswork</div></section><section className="home-preview section-pad"><span className="kicker">The SolveNest method</span><h2>Bring the messy bit.<br /><em>Leave with a way forward.</em></h2><div className="preview-actions"><CTA /><button className="text-link" onClick={() => go('/how-it-works')}>Explore how it works <ArrowUpRight size={16} /></button></div></section></> }

const PageIntro = ({ kicker, title, text }) => <div className="page-intro section-pad"><span className="kicker">{kicker}</span><h1>{title}</h1><p>{text}</p></div>
export function HowItWorksPage() { const steps = [['01', 'Bring the messy bit', 'Tell us what you’re working on, where you’re stuck, and what a good outcome looks like.', FileText], ['02', 'Get a real plan', 'We review your request, set the scope, and send a transparent price and delivery timeline.', Sparkles], ['03', 'Make it yours', 'Work with our expert team, review the result, and leave with something you understand.', ShieldCheck]]; return <><PageIntro kicker="The SolveNest method" title={<>Clarity is a<br /><em>competitive edge.</em></>} text="Great work rarely starts with a perfect brief. Our process turns uncertainty into a sequence you can actually move through." /><section className="process section-pad"><div className="process-grid">{steps.map(([number, title, text, Icon]) => <div className="process-card" key={number}><div className="card-top"><span>{number}</span><Icon size={20} /></div><h3>{title}</h3><p>{text}</p><ArrowUpRight className="card-arrow" size={20} /></div>)}</div></section><section className="page-cta section-pad"><h2>Ready to find<br /><em>your next step?</em></h2><CTA /></section></> }
export function CategoriesPage() { return <><PageIntro kicker="A wider kind of help" title={<>Good support<br /><em>meets you there.</em></>} text="From a first idea to a final review, get focused help without handing over ownership of your learning." /><section className="category-band section-pad"><div className="category-list">{categories.map((category, index) => <button key={category} onClick={() => go('/submit')}><span>0{index + 1}</span><strong>{category}</strong><ArrowUpRight size={20} /></button>)}</div></section></> }
export function PricingPage() { return <><PageIntro kicker="No mystery maths" title={<>You see the plan<br />before the <em>price.</em></>} text="Each request is different. That’s why we scope first, then give you a quote you can accept or decline. No subscriptions. No surprise add-ons." /><section className="pricing section-pad"><div className="pricing-note"><p>AI helps us understand complexity. Our team reviews the scope, sets the official price, and confirms delivery before you commit.</p><CTA>Start with your brief</CTA></div><div className="quote-card"><div className="quote-header"><span><span className="live-dot" /> Sample task plan</span><span>SN / 0247</span></div><div className="quote-title">Research presentation<br /><strong>on sustainable cities</strong></div><div className="quote-row"><span>Scope</span><b>Review + structure + slides</b></div><div className="quote-row"><span>Delivery</span><b>5 working days</b></div><div className="quote-footer"><div><small>Estimated range</small><strong>LKR 8,500 — 12,000</strong></div><Check size={24} /></div></div></section></> }
export function AboutPage() { return <><PageIntro kicker="Why SolveNest exists" title={<>More than an answer.<br /><em>A better way forward.</em></>} text="We believe academic support should make you more capable, not less. SolveNest brings together thoughtful people, intelligent tools, and a process designed around trust." /><section className="about section-pad"><div className="about-stamp">SN<br /><span>EST. 2024</span></div><div className="about-principles"><div><span>01</span><h3>Human oversight</h3><p>Technology accelerates the process. People stay accountable for the decision.</p></div><div><span>02</span><h3>Academic integrity</h3><p>Support should strengthen your understanding, not replace your ownership.</p></div></div></section></> }
export function FaqPage() { const [active, setActive] = useState(0); return <><PageIntro kicker="Questions, answered" title={<>Start with<br /><em>certainty.</em></>} text="A few useful answers before you share your first brief." /><section className="faq section-pad"><div className="faq-list">{faqs.map(([question, answer], index) => <div className={active === index ? 'faq-item active' : 'faq-item'} key={question}><button onClick={() => setActive(active === index ? -1 : index)}><span>{question}</span><ChevronDown size={18} /></button>{active === index && <motion.p initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}>{answer}</motion.p>}</div>)}</div></section></> }
export function SubmitPage() { const [brief, setBrief] = useState(''); const [submitted, setSubmitted] = useState(false); return <><PageIntro kicker="01 / Begin here" title={<>What are you<br /><em>working through?</em></>} text="No polished prompt required. A sentence is enough to start." /><section className="submit-section section-pad"><div className="brief-box">{submitted ? <div className="submitted"><div className="success-icon"><Check /></div><h3>Your first step is in.</h3><p>We’ll turn this into a clear plan. This prototype is ready for the next product layer.</p><button className="dark-button" onClick={() => setSubmitted(false)}>Edit brief</button></div> : <><textarea value={brief} onChange={(event) => setBrief(event.target.value)} placeholder="I’m working on..." /><div className="brief-footer"><span><CircleHelp size={15} /> Keep it simple. You can add files later.</span><button className="dark-button" disabled={!brief.trim()} onClick={() => setSubmitted(true)}>Continue <ArrowUpRight size={16} /></button></div></>}</div></section></> }
export function LoginPage() { return <><PageIntro kicker="Welcome back" title={<>Keep your work<br /><em>moving forward.</em></>} text="Log in to see your requests, plans, messages, and delivery updates." /><section className="auth-panel section-pad"><div className="auth-card"><label>Email address<input type="email" placeholder="you@example.com" /></label><label>Password<input type="password" placeholder="Your password" /></label><button className="dark-button">Log in <ArrowUpRight size={16} /></button><p>New to SolveNest? <button onClick={() => go('/submit')}>Start a request</button></p></div></section></> }
