import { useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowUpRight, Check, ChevronDown, Clock3, FileCheck2, LockKeyhole, Mail, ShieldCheck, Users } from 'lucide-react'
import { Orb } from './Pages.jsx'

const navigate = (path) => { window.location.assign(path) }
const CTA = ({ children = 'Start a request' }) => <button className="lime-button" onClick={() => navigate('/submit')}>{children} <ArrowUpRight size={17} /></button>
const Intro = ({ kicker, title, text }) => <div className="page-intro section-pad"><span className="kicker">{kicker}</span><h1>{title}</h1><p>{text}</p></div>

export function SourceHomePage() { return <><section className="hero section-pad"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Academic support, with a better way</div><h1>Submit once.<br /><em>Move forward</em><br />with clarity.</h1><p className="hero-lede">Submit your academic challenge once and receive a clear, guided, and accountable path from requirements to delivery.</p><div className="hero-cta"><CTA>Share your challenge</CTA><button className="play-button" onClick={() => navigate('/how-it-works')}><span>▶</span> See the full process</button></div><div className="trust-line"><div className="avatar-stack"><i>AK</i><i>NM</i><i>RJ</i></div><span>Built for school, university & early-career work in Sri Lanka</span></div></div><Orb /></section><section className="signal-strip"><div>AI-assisted intake</div><div className="strip-line" /><div>Human decisions · Quality review · Student ownership</div></section><section className="home-proof section-pad"><div><span className="kicker">A controlled path, not a guess</span><h2>Know what happens<br /><em>before you commit.</em></h2></div><div className="proof-grid"><div><ShieldCheck /><strong>Clarity before payment</strong><p>See your approved scope, official price, delivery date, and revision allowance first.</p></div><div><Users /><strong>People stay accountable</strong><p>Solvy can recommend a route. Authorized SolveNest staff make the final decisions.</p></div><div><FileCheck2 /><strong>Reviewed before delivery</strong><p>Internal quality review comes before work reaches you.</p></div></div></section></> }

export function SourceHowPage() { const steps = [['01', 'Submit & validate', 'Share your title, category, level, deadline, requirements, rubric, and supporting files. The system checks the request and files before staff access.'], ['02', 'Solvy analyses', 'AI suggests category, complexity, effort, missing information, delivery risk, and policy concerns. It recommends; it never promises.'], ['03', 'A human reviews', 'An authorized admin decides feasibility, confirms scope, sets the official LKR quote, and proposes a delivery plan.'], ['04', 'Approve & pay', 'Accept or decline the quote. If accepted, secure Stripe payment confirms the task before execution begins.'], ['05', 'Expert work & QA', 'An internal expert works within scope, then a quality reviewer checks the deliverable before release.'], ['06', 'Receive & refine', 'Download the delivery, request an eligible in-scope revision, or approve and close. The initial policy supports two revisions within seven days.']]; return <><Intro kicker="The accountable workflow" title={<>A clear path from<br /><em>stuck to delivered.</em></>} text="SolveNest combines AI-assisted intake, human oversight, internal expertise, quality review, secure delivery, and visible task states." /><section className="workflow section-pad">{steps.map(([number, title, text]) => <div className="workflow-step" key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div><ArrowUpRight size={20} /></div>)}</section><section className="page-cta section-pad"><h2>Bring us the<br /><em>messy middle.</em></h2><CTA /></section></> }

const categoryData = [['Information Technology', 'Programming assignments, web development, databases, software documentation, and beginner AI tasks.'], ['Cybersecurity', 'Ethical, defensive, and report-focused security work within approved safety boundaries.'], ['Academic Writing', 'Essays, reports, journals, editing, structure, citation, and formatting support.'], ['O/L & A/L support', 'School-level explanations, revision guidance, and coursework organization.']]
export function SourceCategoriesPage() { return <><Intro kicker="Start focused" title={<>Support for the<br /><em>work in front of you.</em></>} text="We begin with a deliberately focused set of approved domains. Unsupported or ambiguous requests go through feasibility review instead of entering execution automatically." /><section className="source-category-grid section-pad">{categoryData.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p><button className="text-link" onClick={() => navigate('/submit')}>Tell us about this work <ArrowUpRight size={16} /></button></article>)}</section><section className="integrity-note section-pad"><div><span className="kicker">Our service boundary</span><h2>Support should make<br /><em>you more capable.</em></h2></div><p>We prioritize tutoring, explanation, feedback, editing, research guidance, project mentorship, structure, formatting, debugging, and review of student-created work. We do not support impersonation, exam cheating, fraudulent documents, or harmful activity.</p></section></> }

export function SourcePricingPage() { return <><Intro kicker="Pay per approved task" title={<>Transparent scope.<br /><em>No surprise price.</em></>} text="AI creates a preliminary range. An authorized admin reviews the requirements and sets the official price, deadline, scope, and revision allowance before you pay." /><section className="pricing-details section-pad"><div className="pricing-facts">{[['01', 'Estimated range', 'Based on complexity, effort, scope, and timing.'], ['02', 'Official quote', 'Final price, currency, included and excluded scope, delivery date, and expiry.'], ['03', 'Secure payment', 'Accepted quotes move to Stripe checkout. Work starts after confirmed payment.'], ['04', 'Clear close', 'Initial policy includes two in-scope revisions within seven days after delivery.']].map(([n, t, d]) => <div key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div><div className="quote-card"><div className="quote-header"><span><span className="live-dot" /> Sample official plan</span><span>SN / 0247</span></div><div className="quote-title">Research presentation<br /><strong>on sustainable cities</strong></div><div className="quote-row"><span>Scope</span><b>Review + structure + slides</b></div><div className="quote-row"><span>Delivery</span><b>5 working days</b></div><div className="quote-row"><span>Revisions</span><b>2 within 7 days</b></div><div className="quote-footer"><div><small>Illustrative range</small><strong>LKR 8,500 — 12,000</strong></div><Check size={24} /></div></div></section></> }

export function SourceAboutPage() { return <><Intro kicker="The SolveNest standard" title={<>Premium support<br /><em>with accountability.</em></>} text="SolveNest is a Sri Lankan academic-support operation built around clarity before commitment, student ownership, controlled quality, and an auditable workflow." /><section className="about-values section-pad">{[['Human oversight', 'AI accelerates intake, classification, estimation, and routing. Authorized people make feasibility, commercial, integrity, and quality decisions.'], ['Student ownership', 'The goal is guidance that improves understanding and capability, not work submitted as if it were independently created by a student.'], ['Privacy by design', 'Submissions are intended for private storage, controlled access, malware scanning, signed links, retention rules, and auditability.'], ['A measured beginning', 'We start with approved categories and expand only when demand, quality, delivery, and student satisfaction support it.']].map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</section><section className="about-statement section-pad"><div className="about-stamp">SN<br /><span>COLOMBO</span></div><div><h2>Not an open marketplace.<br /><em>A trusted operating system.</em></h2><p>Internal experts, quality reviewers, administrators, and students each have a clear role in the journey.</p></div></section></> }

export function SourceFaqPage() { const [active, setActive] = useState(0); const items = [['Is SolveNest an unrestricted homework service?', 'No. SolveNest provides permitted academic guidance, feedback, research support, editing, mentoring, structure, and review. Requests involving cheating, impersonation, fraudulent documents, or harmful activity are restricted.'], ['How does pricing work?', 'AI prepares an estimate, then an authorized admin confirms feasibility, scope, official LKR price, deadline, and revision allowance. You decide whether to accept before payment.'], ['When does work begin?', 'After you accept the quote and the backend confirms Stripe payment, the task can be assigned to an internal expert.'], ['What happens after delivery?', 'You receive a quality-reviewed delivery. You can approve and close it or request an eligible in-scope revision. The initial policy supports two revisions within seven days.'], ['Are my files private?', 'Production uploads should use private object storage, file validation, malware scanning, limited access, and short-lived signed URLs.']]; return <><Intro kicker="Questions, answered" title={<>Start with<br /><em>certainty.</em></>} text="The important parts of the SolveNest promise, in plain language." /><section className="faq section-pad"><div className="faq-list">{items.map(([question, answer], index) => <div className={active === index ? 'faq-item active' : 'faq-item'} key={question}><button onClick={() => setActive(active === index ? -1 : index)}><span>{question}</span><ChevronDown size={18} /></button>{active === index && <motion.p initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}>{answer}</motion.p>}</div>)}</div></section></> }

export function ContactPage() { return <><Intro kicker="We’re listening" title={<>Questions, ideas,<br /><em>or a tricky brief?</em></>} text="Tell us what you need help understanding. A member of the SolveNest team can guide you to the right next step." /><section className="contact-grid section-pad"><div><Mail /><h3>Email the team</h3><p>hello@solvenest.lk</p><small>For general questions and new requests.</small></div><div><Clock3 /><h3>Response window</h3><p>Within one working day</p><small>We are building for students across Sri Lanka.</small></div><div><LockKeyhole /><h3>Task-specific help</h3><p>Use your task workspace</p><small>Messages stay attached to the request they belong to.</small></div></section></> }
export function RegisterPage() { return <><Intro kicker="Start with clarity" title={<>Create your<br /><em>SolveNest account.</em></>} text="Save your requests, review quotes, track delivery, and keep your work history in one place." /><section className="auth-panel section-pad"><div className="auth-card"><label>Full name<input type="text" placeholder="Your name" /></label><label>Email address<input type="email" placeholder="you@example.com" /></label><label>Password<input type="password" placeholder="Create a password" /></label><label className="policy-check"><input type="checkbox" /> I agree to use SolveNest within its academic-integrity policy.</label><button className="dark-button">Create account <ArrowUpRight size={16} /></button><p>Already have an account? <button onClick={() => navigate('/login')}>Log in</button></p></div></section></> }
